# Generated by Django 3.0 on 2020-02-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='password',
        ),
        migrations.AddField(
            model_name='movies',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies2',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reg',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reg',
            name='seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
